### ISSUE TITLE
A better implementation of `_intToFloat`.

### ISSUE THREAD

**Issue by SkepticalHippo** [SkepticalHippo/crypto-random#2]
The current implementation of `_intToFloat` is not too elegant and might not be the most efficient way of doing this.

Another option would be to use `parseFloat('0.'+integer)`.

Suggestions welcome.

**Comment by gezeta-id** [comment]
It's not really about elegance or performance. Both of those solutions suffer from the same **error**.

Take into account that you're obtaining random UInt32 numbers. So, say you get a bunch of them...

```
4181721143
1840805934
1944009376
648875246
2965102778
4241463506
632645452
2906291726
3418105154
14577198
3012716542
944519484
4081219935
```

Now, you try to project them on `[0,1)` by either dividing by `Math.pow(10, number.toString().length)` or by planting a `0.` before them. What does this get you?

```
4181721143 -> 0.4181721143
1840805934 -> 0.1840805934
1944009376 -> 0.1944009376
648875246  -> 0.648875246
2965102778 -> 0.2965102778
4241463506 -> 0.4241463506
632645452  -> 0.632645452
2906291726 -> 0.2906291726
3418105154 -> 0.3418105154
14577198   -> 0.14577198
3012716542 -> 0.3012716542
944519484  -> 0.944519484
4081219935 -> 0.4081219935
```

But this is clearly not correct at all. The first problem is that for integers left-side zeros don't matter, but for decimals (to the left but after the comma), they do.

```
4181721143 -> 0.4181721143
1840805934 -> 0.1840805934
1944009376 -> 0.1944009376
648875246  -> 0.0648875246
2965102778 -> 0.2965102778
4241463506 -> 0.4241463506
632645452  -> 0.0632645452
2906291726 -> 0.2906291726
3418105154 -> 0.3418105154
14577198   -> 0.0014577198
3012716542 -> 0.3012716542
944519484  -> 0.0944519484
4081219935 -> 0.4081219935
```

But this, still, is not correct. the largest number a UInt32 can hold is 4294967295, not 9999999999. So, if you did this but correctly took into account the different sizes and filled with leading zeroes, you'd still have the problem that you wouldn't get any number larger than 0.4294967295.

The correct solution, is dividing by 4294967295

```
4181721143/4294967295 -> 0.973632825532377
1840805934/4294967295 -> 0.42859603055487294
1944009376/4294967295 -> 0.45262495438862244
648875246/4294967295  -> 0.15107804121241858
2965102778/4294967295 -> 0.6903667884623554
4241463506/4294967295 -> 0.9875426783663087
632645452/4294967295  -> 0.14729924782814907
2906291726/4294967295 -> 0.6766737733680461
3418105154/4294967295 -> 0.7958396232677251
14577198/4294967295   -> 0.0033940183938001326
3012716542/4294967295 -> 0.70145273178384
944519484/4294967295  -> 0.21991307945454333
4081219935/4294967295 -> 0.9502330645802973
```

Note, though, that if you go this route, it would be better to separate the obtaining of the random values from the projection into the `[0,1)` range into two different functions, because not doing so, would mean that the `range` method would make 2 projections, first on `[0,1)`, and then from this into `[min, max)`. The bias here would be subtle, but the multiple operations may indeed result in a small rounding unevenness on the distribution of the results.

So, instead, you'd make the internal/local `get*RandomValue` functions return a random UInt32 integer. Then, `value` would project it into `[0,1)` and `range` would project it into `[min, max)` so that each would only make the minimum amount of manipulations and you'd introduce as little unevenness as you can.

**Comment by SkepticalHippo** [comment]
@gezeta-id thanks very much for this. This explains a lot of the issues I had with the distribution. I'll look into the 2 projection bias further 👍
